/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    InputText: typeof import('primevue/inputtext')['default']
    README: typeof import('./core/components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./core/components/TheCounter.vue')['default']
    TheFooter: typeof import('./core/components/TheFooter.vue')['default']
    TheInput: typeof import('./core/components/TheInput.vue')['default']
  }
}
